export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const DELETE_INGREDIENT = "DELETE_INGREDIENT";
export const FETCH_INITIAL_INGREDIENTS = "FETCH_INITIAL_INGREDIENTS";
export const FETCH_INGREDIENTS_ERROR = "FETCH_INGREDIENTS_ERROR";

export const PURCHASE_BURGER_SUCCESS = "PURCHASE_BURGER_SUCCESS";
export const PURCHASE_INIT = "PURCHASE_INIT";

export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const DATA_FAIL = "DATA_FAIL";
export const HANDLE_DATA_START = "HANDLE_DATA_START";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";
